output_path: {
  features: './Outputs/features.pkl',
  tokenizer: './Outputs/tokenizer.pkl'
}
input_path: {
  images: './Data/ImagesTest/',
  captions: './Data/captionsTest.txt'}
hyperparameters: {
  'embedding_dim': [4, 12],
  'dense_units': [8, 16],
  'batch_size': [1, 2],
  'epochs': 10,
  'optimizer': ['adam', 'rmsprop'],
  'image_dropout': [0.25,],
  'text_dropout': [0.25],
}
caption_preprocessing: {
  prefix: 'startseq',
  suffix: 'endseq'
}