output_path: {
  features: './Outputs/features.pkl',
  tokenizer: './Outputs/tokenizer.pkl'
}
input_path: {
  images: './Data/Images/',
  captions: './Data/captions.txt'}
hyperparameters: {
  'embedding_dim': [64, 128],
  'dense_units': [64, 128],
  'batch_size': 32,
  'epochs': 20,
  'optimizer': ['adam'],
  'image_dropout': [0.25, 0.35],
  'text_dropout': [0.25, 0.35]
}
caption_preprocessing: {
  prefix: 'startseq',
  suffix: 'endseq'
}
train_ratio: 0.9
evaluate_sample: 100